CD 관련 작업 추가 : deployment가 실패한 경우에는 main 브랜치로 push한 것을 취소 시킨다.

diff --git a/.github/workflows/azure-webapps-deploy.yml b/.github/workflows/azure-webapps-deploy.yml
--- a/.github/workflows/azure-webapps-deploy.yml
+++ b/.github/workflows/azure-webapps-deploy.yml
@@ -47,9 +47,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-
     needs: build
-
     steps:
       - name: Lowercase the repo name
         run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
@@ -60,3 +58,9 @@ jobs:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
+      - name: Check deployment status # deployment가 fail했을 때 main 브랜치로 push되는 것을 막기
+        if: ${{ failure() }}
+        run: exit 1
+      - name: Prevent push to main branch on deployment failure
+        if: ${{ failure() }}
+        run: git reset --hard HEAD^
